# events -> Nginx’in connection handling (bağlantı yönetimi) ile ilgili ayarlarının olduğu blok.
# yani, istemcilerden (browser, API client vb.) gelen bağlantıları nasıl kabul ettiği, yönettiği ve kapattığı sürecin tamamıdır.
# TCP bağlantısı, https tls handshake vb. süreçlerin ele alınması. bağlantı en sonunda ya kapatır ya da açık tutulur (keep-alive).
events {}

# HTTP/HTTPS trafiğinin işlendiği ana katmandır.
http {
	include /etc/nginx/mime.types;	#  (Dosya uzantılarını Content-Type header ile eşler.) Tarayıcıya gönderilen dosyaların türlerini (css, js, html, png vb.) doğru tanımasını sağlar. Yoksa web sitendeki tasarımlar bozuk görünebilir.
    default_type application/octet-stream;	# Eğer dosya türü bilinmiyorsa, tarayıcıya "bu indirilebilir bir dosya" demesini sağlar.

	server {
		listen 443 ssl;
		server_name atursun.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;	# 1.2 ve 1.3 sürümlerini destekle, eski sürümleri (TLSv1.0, TLSv1.1) destekleme. 
		ssl_ciphers HIGH:!aNULL:!MD5; # Güçlü şifreleme algoritmaları seçiliyor (!aNULL → authentication olmayanlar yasak, !MD5 → kırılmış algoritma yasak, HIGH → güçlü algoritmalar)

		# Bu ikisi birlikte: HTTPS handshake yapar, Sunucunun kimliğini doğrular
		ssl_certificate /etc/ssl/certs/cert.pem;	# public certificate
		ssl_certificate_key /etc/ssl/private/key.pem; # private key

		root /var/www/html;	# Web sunucusunun kök dizini, yani web içeriğinin bulunduğu yer. Nginx, gelen isteklerde bu dizini temel alarak dosya arar.
		index index.php;	# Siteye girildiğinde otomatik açılacak ilk dosya, WordPress'in ana dosyası bu olduğundan ilk bunu arayacak.

		# Routing (yönlendirme): Gelen isteği doğru (sayfa, API, servis) yönlendirmektir.
		location / { # ana lokasiyon, yani site köküne gelen istekler için geçerli. Örneğin, istenen dosya var mı kalsör var mı yoksa PHP'ye yönlendir(/index.php?$args;).
			try_files $uri $uri/ /index.php?$args;
		}

		# .php uzantılı dosyalar için özel bir konfigürasyon. PHP dosyaları doğrudan sunulmaz, bunun yerine PHP-FPM (FastCGI Process Manager) tarafından işlenir.
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000; # nginx PHP’yi kendisi calistirmiyor, WordPress/PHP-FPM konteynerine 9000 portu üzerinden iletiyor.
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;	# PHP’ye şu dosyayı çalıştır diyor: /var/www/html/index.php
		    fastcgi_param PATH_INFO $fastcgi_path_info;
		}
	}
}
